#ifndef ITEMS_H
#define ITEMS_H

#include <stdbool.h>

typedef enum {
    EMPTY                     = 0x00,
    ITEM_START                = 0x01,
    CREST_KEY                 = 0x01,
    BOTTLE_OF_OIL             = 0x02,
    FRAGMENTS_OF_A_CREST      = 0x03,
    DRAGON_TEARS              = 0x04,
    PIXIE_FLUTE               = 0x05,
    TREASURE                  = 0x06,
    RUSTY_KEY                 = 0x07,
    ORNATE_KEY                = 0x08,
    RING_OF_THE_KINGDOM       = 0x09,
    ORB                       = 0x0a,
    GOLDEN_KEY                = 0x0b,
    LIQUID_SUNSET             = 0x0c,
    NIGHT_ELIXIR              = 0x0d,
    FOREST_NECTAR             = 0x0e,
    PRIMITIVE_MAN_STATUE      = 0x0f,
    APEMAN_SCULPTURE          = 0x10,
    FAIRY_SCULPTURE           = 0x11,
    ELF_STATUE                = 0x12,
    ANCIENT_COIN              = 0x13,
    PICKAX                    = 0x14,
    RING_OF_THE_DEAD          = 0x15,
    BLUE_RING                 = 0x16,
    GREEN_RING                = 0x17,
    LEVER                     = 0x18,
    SLIPPER                   = 0x19,
    DIRTY_SLIPPER             = 0x1a,
    PAIR_OF_SLIPPERS          = 0x1b,
    JEZIBELS_PENDANT          = 0x1c,
    STAFF_OF_AGES             = 0x1d,
    ROPE                      = 0x1e,
    CEMETERY_KEY              = 0x1f,
    FLOWER                    = 0x20,
    FLINT                     = 0x21,
    FANG                      = 0x22,
    DRAGON_EYE                = 0x23,
    DRAGON_FLUTE              = 0x24,
    BURNING_CANDLE            = 0x25,
    CHIPPED_VIOLIN            = 0x26,
    VIOLIN_WITHOUT_STRINGS    = 0x27,
    BROKEN_VIOLIN             = 0x28,
    DUNGEON_KEY               = 0x29,
    MAP                       = 0x2a,
    BONE                      = 0x2b,
    STAR_CREST                = 0x2c,
    IRON_BAR                  = 0x2d,
    CROWBAR                   = 0x2e,
    HAIR_OF_GIANT             = 0x2f,
    MUG                       = 0x30,
    WATER                     = 0x31,
    WATER_WITH_DRAGON_TEARS   = 0x32,
    STONE_OF_THIRST           = 0x33,
    COIN_IN_PARK              = 0x34,
    COIN_IN_PATHWAY_TO_PARK   = 0x35,
    COIN_IN_EXCAVATION_AREA   = 0x36,
    COIN_IN_GATE_KEEPERS_ROOM = 0x37,
    LOST_COIN                 = 0x38,
    NAIL                      = 0x39,
    BROOCH                    = 0x3a,
    JEWELRY_BOX               = 0x3b,
    FRUIT                     = 0x3c,
    GAUNTLET                  = 0x3d,
    CUP                       = 0x3e,
    ARTWORK                   = 0x3f,
    POISONOUS_HERB            = 0x40,
    BRACELET                  = 0x41,
    PRECIOUS_STONE            = 0x42,
    BROKEN_SWORD              = 0x43,
    QUILL                     = 0x44,
    PLATE                     = 0x45,
    BROKEN_LANCE              = 0x46,
    ITEM_END                  = 0x47,

    BOOK_START                = 0x4b,
    DNARTH_FAMILY_CHRONICLES  = 0x4b,
    THE_FINAL_BATTLE          = 0x4c,
    THE_SPEECHES_OF_LORD_JAIR = 0x4d,
    BLANK_BLUE_BOOK           = 0x4e,
    THE_ABYSS_OF_DARKNESS     = 0x4e,
    BLANK_GREEN_BOOK          = 0x4f,
    THE_AGE_OF_ENLIGHTENMENT  = 0x4f,
    BLANK_RED_BOOK            = 0x50,
    THE_SECRETS_OF_THE_STAFF  = 0x50,
    STUDENTS_DIARY            = 0x51,
    ACOLYTES_DIARY            = 0x52,
    PERSONAL_JOURNAL          = 0x53,
    MEMOIRS                   = 0x54,
    NOVICES_JOURNAL           = 0x55,
    TRIALS_OF_THE_KINGDOM     = 0x56,
    THE_BROTHERHOOD_REPORT    = 0x57,
    THE_WRITINGS_OF_KONNOR    = 0x58,
    THE_HOUSE_OF_DRESLIN      = 0x59,
    MEMORANDUM                = 0x5a,
    THE_LAST_DRAGON           = 0x5b,
    OF_RIDING_DRAGONS         = 0x5c,
    RESEARCH_LOG              = 0x5d,
    MUSINGS_OF_A_LUNATIC      = 0x5e,
    THE_BOOK_OF_ORDERS        = 0x5f,
    LAWS_OF_MAGIC             = 0x60,
    FAMILY_DIARY              = 0x61,
    WORDS_OF_DNARTH           = 0x62,
    ARTIFACTS_OF_POWER        = 0x63,
    MAGICAL_ELIXIRS           = 0x64,
    JOURNAL                   = 0x68,
    WATCHMANS_MEMO            = 0x69,
    REPORT                    = 0x6a,
    OFFICIALS_ARTICLE         = 0x6b,
    LECTURE_NOTES             = 0x6c,
    PERSONAL_LETTER           = 0x6d,
    THE_INNER_CHAMBER         = 0x6e,
    TRAVELOGUE                = 0x6f,
    TRAVEL_GUIDE              = 0x70,
    PETITION                  = 0x71,
    RECEIPT                   = 0x72,
    PERSONAL_NOTE             = 0x73,
    BOOK_END                  = 0x74,
} itemId_t;

// Shuffling a critical item into any omitted location could lead to a soft-lock.
#define ITEMS_DUNGEON BONE
#define ITEMS_SEWERS_1 MAP, IRON_BAR
#define ITEMS_SEWERS_2 PICKAX
#define BOOKS_SEWERS_2 JOURNAL
#define ITEMS_DISCIPLES_TOWER_1 LIQUID_SUNSET, PRIMITIVE_MAN_STATUE, APEMAN_SCULPTURE, FAIRY_SCULPTURE, ELF_STATUE, ANCIENT_COIN, ROPE
#define BOOKS_DISCIPLES_TOWER_1 THE_FINAL_BATTLE, THE_SPEECHES_OF_LORD_JAIR, THE_AGE_OF_ENLIGHTENMENT, THE_SECRETS_OF_THE_STAFF, \
OF_RIDING_DRAGONS, THE_BOOK_OF_ORDERS, LAWS_OF_MAGIC, ARTIFACTS_OF_POWER, WATCHMANS_MEMO, LECTURE_NOTES
#define ITEMS_DISCIPLES_TOWER_2 PIXIE_FLUTE
#define BOOKS_DISCIPLES_TOWER_2 THE_ABYSS_OF_DARKNESS, STUDENTS_DIARY, THE_HOUSE_OF_DRESLIN, REPORT, PERSONAL_LETTER, PERSONAL_NOTE
#define ITEMS_CATHEDRAL_1 DRAGON_TEARS, ORNATE_KEY, GOLDEN_KEY, CROWBAR
#define ITEMS_CATHEDRAL_2 NAIL
#define ITEMS_LAKMIRS_TOWER_1 BOTTLE_OF_OIL, RUSTY_KEY, HAIR_OF_GIANT, MUG
#define BOOKS_LAKMIRS_TOWER_1 ACOLYTES_DIARY, MAGICAL_ELIXIRS, OFFICIALS_ARTICLE, RECEIPT
#define ITEMS_LAKMIRS_TOWER_2 /*STAR_CREST*/
#define ITEMS_LAKMIRS_TOWER_3 CREST_KEY, NIGHT_ELIXIR, FOREST_NECTAR, QUILL
#define BOOKS_LAKMIRS_TOWER_3 PERSONAL_JOURNAL, MEMOIRS, THE_INNER_CHAMBER
#define ITEMS_LAKMIRS_TOWER_4 RING_OF_THE_DEAD, BLUE_RING, GREEN_RING
#define ITEMS_CATHEDRAL_3 JEZIBELS_PENDANT
#define BOOKS_CATHEDRAL_3 FAMILY_DIARY
#define ITEMS_DISCIPLES_TOWER_3 SLIPPER, CEMETERY_KEY
#define ITEMS_VILLAGE_1 FLOWER, COIN_IN_PARK, COIN_IN_PATHWAY_TO_PARK, COIN_IN_EXCAVATION_AREA, COIN_IN_GATE_KEEPERS_ROOM, \
ARTWORK, POISONOUS_HERB, BRACELET, PRECIOUS_STONE, BROKEN_SWORD, PLATE, BROKEN_LANCE
#define BOOKS_VILLAGE_1 DNARTH_FAMILY_CHRONICLES, MUSINGS_OF_A_LUNATIC, PETITION
#define ITEMS_MERCHANT BROOCH, JEWELRY_BOX, FRUIT, GAUNTLET /*CUP*/
#define ITEMS_VILLAGE_2 DIRTY_SLIPPER /*STONE_OF_THIRST*/
#define ITEMS_VILLAGE_3 ORB
#define BOOKS_VILLAGE_3 TRAVELOGUE, TRAVEL_GUIDE
#define ITEMS_DISCIPLES_TOWER_4 TREASURE
#define ITEMS_VILLAGE_4 DUNGEON_KEY
#define ITEMS_VILLAGE_5 /*LEVER*/ FLINT, FANG
#define BOOKS_VILLAGE_5 RESEARCH_LOG
#define ITEMS_TRIALS_1 FRAGMENTS_OF_A_CREST
#define BOOKS_TRIALS_1 NOVICES_JOURNAL, TRIALS_OF_THE_KINGDOM, THE_BROTHERHOOD_REPORT, THE_WRITINGS_OF_KONNOR
#define ITEMS_TRIALS_2 RING_OF_THE_KINGDOM
#define ITEMS_DISCIPLES_TOWER_5 DRAGON_FLUTE
#define ITEMS_DRAGON_TOWER_1 DRAGON_EYE
#define BOOKS_DRAGON_TOWER_1 THE_LAST_DRAGON
#define BOOKS_DRAGON_TOWER_2 WORDS_OF_DNARTH

#define ALL_TOWER_1 ITEMS_DUNGEON, ITEMS_SEWERS_1, ITEMS_SEWERS_2, BOOKS_SEWERS_2, ITEMS_DISCIPLES_TOWER_1, BOOKS_DISCIPLES_TOWER_1, \
ITEMS_DISCIPLES_TOWER_2, BOOKS_DISCIPLES_TOWER_2
#define ALL_TOWER_2 ITEMS_CATHEDRAL_1, ITEMS_CATHEDRAL_2, ITEMS_LAKMIRS_TOWER_1, BOOKS_LAKMIRS_TOWER_1, /*ITEMS_LAKMIRS_TOWER_2,*/ \
ITEMS_LAKMIRS_TOWER_3, BOOKS_LAKMIRS_TOWER_3, ITEMS_LAKMIRS_TOWER_4
#define ALL_VILLAGE ITEMS_CATHEDRAL_3, BOOKS_CATHEDRAL_3, ITEMS_DISCIPLES_TOWER_3, ITEMS_VILLAGE_1, BOOKS_VILLAGE_1, \
ITEMS_VILLAGE_2, ITEMS_VILLAGE_3, BOOKS_VILLAGE_3, ITEMS_DISCIPLES_TOWER_4, ITEMS_VILLAGE_4, ITEMS_VILLAGE_5, BOOKS_VILLAGE_5
#define ALL_TOWER_3 ITEMS_TRIALS_1, BOOKS_TRIALS_1, ITEMS_TRIALS_2
#define ALL_TOWER_4 ITEMS_DISCIPLES_TOWER_5, ITEMS_DRAGON_TOWER_1, BOOKS_DRAGON_TOWER_1, BOOKS_DRAGON_TOWER_2

#define ALL_ITEMS CREST_KEY, BOTTLE_OF_OIL, FRAGMENTS_OF_A_CREST, DRAGON_TEARS, PIXIE_FLUTE, TREASURE, RUSTY_KEY, ORNATE_KEY, \
RING_OF_THE_KINGDOM, ORB, GOLDEN_KEY, LIQUID_SUNSET, NIGHT_ELIXIR, FOREST_NECTAR, PRIMITIVE_MAN_STATUE, APEMAN_SCULPTURE, \
FAIRY_SCULPTURE, ELF_STATUE, ANCIENT_COIN, PICKAX, RING_OF_THE_DEAD, BLUE_RING, GREEN_RING, LEVER, SLIPPER, DIRTY_SLIPPER, \
PAIR_OF_SLIPPERS, JEZIBELS_PENDANT, STAFF_OF_AGES, ROPE, CEMETERY_KEY, FLOWER, FLINT, FANG, DRAGON_EYE, DRAGON_FLUTE, BURNING_CANDLE, \
CHIPPED_VIOLIN, VIOLIN_WITHOUT_STRINGS, BROKEN_VIOLIN, DUNGEON_KEY, MAP, BONE, STAR_CREST, IRON_BAR, CROWBAR, HAIR_OF_GIANT, MUG, \
WATER, WATER_WITH_DRAGON_TEARS, STONE_OF_THIRST, COIN_IN_PARK, COIN_IN_PATHWAY_TO_PARK, COIN_IN_EXCAVATION_AREA, \
COIN_IN_GATE_KEEPERS_ROOM, LOST_COIN, NAIL, BROOCH, JEWELRY_BOX, FRUIT, GAUNTLET, CUP, ARTWORK, POISONOUS_HERB, BRACELET, \
PRECIOUS_STONE, BROKEN_SWORD, QUILL, PLATE, BROKEN_LANCE

#define ALL_BOOKS DNARTH_FAMILY_CHRONICLES, THE_FINAL_BATTLE, THE_SPEECHES_OF_LORD_JAIR, THE_ABYSS_OF_DARKNESS, \
THE_AGE_OF_ENLIGHTENMENT, THE_SECRETS_OF_THE_STAFF, STUDENTS_DIARY, ACOLYTES_DIARY, PERSONAL_JOURNAL, MEMOIRS, NOVICES_JOURNAL, \
TRIALS_OF_THE_KINGDOM, THE_BROTHERHOOD_REPORT, THE_WRITINGS_OF_KONNOR, THE_HOUSE_OF_DRESLIN, MEMORANDUM, THE_LAST_DRAGON, \
OF_RIDING_DRAGONS, RESEARCH_LOG, MUSINGS_OF_A_LUNATIC, THE_BOOK_OF_ORDERS, LAWS_OF_MAGIC, FAMILY_DIARY, WORDS_OF_DNARTH, \
ARTIFACTS_OF_POWER, MAGICAL_ELIXIRS, JOURNAL, WATCHMANS_MEMO, REPORT, OFFICIALS_ARTICLE, LECTURE_NOTES, PERSONAL_LETTER, \
THE_INNER_CHAMBER, TRAVELOGUE, TRAVEL_GUIDE, PETITION, RECEIPT, PERSONAL_NOTE

#define EVERYTHING ALL_ITEMS, ALL_BOOKS

typedef enum {
    MODE_STATIC_BOOKS = 0,
    MODE_SHUFFLE_BOOKS_SEPARATELY = 1,
    MODE_SHUFFLE_BOOKS = 2,
    MODE_SHUFFLE_BOOKS_NO_LOGIC = 3,
    MODE_INPUT_MIN = 1,
    MODE_INPUT_MAX = 4,
} shuffleMode_t;

typedef struct {
    const itemId_t id;
    itemId_t possibleLocations[BOOK_END];
    int numPossibilities;
} item_t;

int compareItems(const void * a, const void * b);
void preprocessItems(shuffleMode_t mode);

bool isValidItem(itemId_t id);
bool isItem(itemId_t id);
bool isBook(itemId_t id);

#endif